### PR TITLE
Input based system

### PR DESCRIPTION
**Pull request by oddaaron00**
I converted the `<span>` system to an `<input>` system and altered some styling to tidy it up. Let me know what you think.

### CODE REVIEW

**Comment by ftyers** [comment]
In general I like this, I didn't like the text box resizing. However perhaps we could automatically size them? I think it isn't a problem to have maybe textwidth + a couple of spaces padding on either side? 

Giving a clue as to the length of the word is not a big issue I think?

**Comment by d33tah** [comment]
It could also be something like shownLength = math.ceil(length / 10) * 10. So 11 and 19 both become 20, but 21 becomes 30.

**Comment by oddaaron00** [comment]
I can't work on this any more today but I've changed it so the length of the input element is based off of the CSS unit `ch` (I also converted that whole input thing to a template literal so it's easier to read). But yeah, make of it what you will haha

**Comment by ftyers** [comment]
Looks good to me!

**Comment by d33tah** [comment]
BTW @oddaaron00 I tried to contact you via your public e-mail. Please respond when you get a chance :)

**Pull request merged**
